#!/bin/bash

if [ $# -ne 1 ]; then
	echo "Potreban je 1 argument, broj od 1 do 10]"
	exit 1
fi

if ! [[ $1 =~ ^[0-9]+$ ]]; then
	echo "Argument mora biti broj"
	exit 1
fi

if [ $1 -lt 1 ] || [ $1 -gt 10 ]; then
	echo "Broj mora biti između 1 i 10"
	exit 1
fi

broj=$1
niz=()
for((i=1;i<=broj;i++)); do
	niz+=($i)
done

echo "${niz[@]}" > brojevi.txt

echo "Stvorena je datoteka brojevi.txt s nizom od 1 do $broj"
